### ISSUE TITLE
Document the Editorial Board in this repo

### ISSUE THREAD

**Issue by hugovk** [python/docs-community#100]
[PEP 732 – The Python Documentation Editorial Board](https://peps.python.org/pep-0732/) was accepted last month, which formed a Documentation Editorial Board to replace the old Documentation Working Group.

Let's update this repo's docs to reflect this.

* [x] https://github.com/python/docs-community/blob/main/README.md -> PR https://github.com/python/docs-community/pull/99
* [x] https://docs-community.readthedocs.io/en/latest/workgroup/index.html

Please could the EB take care of updating https://docs-community.readthedocs.io/en/latest/workgroup/index.html?

There's lots of stuff there about (old WG) practices which the new board is best placed to update. I expect a lot can be deleted and/or replaced with a link to the PEP.

**Comment by willingc** [comment]
@python/editorial-board @hugovk I will take care of removing the old content and create a page for the EB.
