### ISSUE TITLE
Bug in sitemap ?

### ISSUE THREAD

**Issue by amirouche** [python/docs-community#12]
At https://docs.python.org/sitemap.xml the link `https://docs.python.org/en/3/` does not work

**Comment by JulienPalard** [comment]
Fixed in https://github.com/python/docsbuild-scripts/commit/12fad8845fd6fce9ed819f67cd4233229ce9a23f

Thanks for reporting @amirouche!

It may take 24h max to reflect in production.

**Comment by amirouche** [comment]
It works. Thanks!
