### ISSUE TITLE
Docs WG monthly meeting #1

### ISSUE THREAD

**Issue by encukou** [python/docs-community#15]
Hello, Docs WG! I think it's time to plan the long-overdue monthly meetings.
Carol filled me in on some previous conversations, and I'd like to play the role of a project manager -- help make this actually happen.

I'm envisioning a one-hour meeting call, **open to the community** (with moderation, obviously).
Would everyone be OK with meeting over <img src="https://user-images.githubusercontent.com/302922/150822605-d14e4c01-2101-4b05-b730-5e80d862569d.png" height="20px"> **Discord**?

For me it would be convenient to combine this meeting with the Steering Council one, so I'll propose **Monday, Feb 7th, <del>17:30 UTC</del> <ins>[22:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220207T2200)</ins>**. But I'm quite flexible.
Does this work for you, and if not, what time(s) could you make it? If you don't want to share details here, I'm at encukou@gmail.com

@willingc  @mariatta @nedbat @JulienPalard

*Edit:*
As for the platform, no one seems to be against Discord. If you already have an account there, please join with `sMWqvzXvde`. Or contact me at [encukou@gmail.com](mailto:encukou@gmail.com) for a direct link -- this should be public, but I want to avoid any invite-harvesting bots.

**Comment by nedbat** [comment]
I started a Doodle poll to find a time: https://doodle.com/poll/g9r3y3zp5n3c9wvk

**Comment by encukou** [comment]
Thanks for the doodle! Yes, that's a better way to organize this.

Looks like the results are in -- at least enough results to show we can't pick a time that's good for everyone :)

So, let's do Monday, Feb 7, [22:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220207T2200)? I marked that as "no" since it's 23:00 to midnight here, but I can get some extra coffee. And everyone else so far can make it.
Ned, could you finalize the slot on Doodle?

As for the platform, no one seems to be against Discord. If you already have an account there, please join with `sMWqvzXvde`. Or contact me at encukou@gmail.com for a direct link -- this should be public, but I want to avoid any invite-harvesting bots.

**Comment by pradyunsg** [comment]
> `sMWq...`

Oh, this is the server invite code! I didn't realise that when I first read it. Replace python in https://discord.com/invite/python, with that code.

**Comment by encukou** [comment]
> Oh, this is the server invite code

Yes. You can also put it directly in Discord's "Join a server" box.

**Comment by pauleveritt** [comment]
Thanks for kicking this off @encukou ... I can help you on admin and janitor work.

**Comment by encukou** [comment]
@cam-gerlach (& other active PEP editors): I wonder if you'd be interested in the [documentation working group](https://docs-community.readthedocs.io/en/latest/workgroup/workgroup_charter.html).

**Comment by CAM-Gerlach** [comment]
Yes indeed, if after due consideration you all think I would be a good fit—thanks for mentioning me, @encukou ! As usual, I feel a bit awed to be talking to such Python luminaries as yourselves, but I do have a background in technical writing and copyediting; experience in creating and/or maintaining the [Spyder](https://www.spyder-ide.org/) docs, docs theme, website and website theme, the Docrepr Sphinx doc generator, and now as a PEP Editor; and have always had an interest in helping improve the Python docs. 

As a non-core dev and a NASA research scientist rather than a programmer by formal training, I'm a bit of an outsider here, but if that's something that you think would be valuable to have, I'd be honored to apply to join. If so, let me know the next steps from my end. Thanks!

**Comment by encukou** [comment]
I'm awed by being called a “luminary”, but

> As a non-core dev and a NASA research scientist rather than a programmer by formal training, I'm a bit of an outsider here

How can we make you feel less like an outsider? The docs aren't aimed only at traditionally-trained professional programmers who already know Python's insides! 

> have always had an interest in helping improve the Python docs.

And I always thought your experience and energy could be better spent on docs with a wider reach, but didn't want to butt in as a self-appointed manager setting volunteers' priorities :)
Anyway, as I see it, Docs WG is here to empower people like you. We just don't quite know how to do that, yet.

> let me know the next steps from my end

If you can make it to the meeting on Monday, please join the Discord space and we'll talk there.
If not, can I meet with just you? See the doodle Ned linked for my availability. You can mail me at encukou@gmail.com so we don't spam here.
(You can join Discord either way. It's pretty quiet so far.)

**Comment by CAM-Gerlach** [comment]
> How can we make you feel less like an outsider? The docs aren't aimed only at traditionally-trained professional programmers who already know Python's insides!

Oh, you all certainly didn't—sorry if I sent that impression! It had more to do with the fact that I don't really fit the mold of a traditional programmer, combined with the fact that I've only contributed a few PRs to CPython and Python core docs. You've made me feel more than welcome with your kind words and thoughtful questions, thanks :) But I certainly hope it'll be helpful having someone who's less of an expert to consult with.

 > And I always thought your experience and energy could be better spent on docs with a wider reach, but didn't want to butt in as a self-appointed manager setting volunteers' priorities :)
 
You're too kind; I had no idea anything I'd done would have caught the attention of anyone like you (aside from my being too long-winded and leaving too many detailed PR review comments, heh). But I very much appreciate it!

 > If you can make it to the meeting on Monday, please join the Discord space and we'll talk there.
 
 I'd love to, but unfortunately I have a flight at that exact time, and it doesn't look like its really possible to move it around at this point. If the flight gets delayed, I can try to join from the airport.

> If not, can I meet with just you? See the doodle Ned linked for my availability. You can mail me at [encukou@gmail.com](mailto:encukou@gmail.com) so we don't spam here.

Sure! 12:00 Tuesday the 8th looks pretty good. I'll join the Discord, and you can email me at CAM.Gerlach@Gerlach.CAM (yes, that's .CAM), though honestly a Discord or Python Discuss DM might reach me faster/more reliably, given the low SNR of my email inbox recently. Thanks, and looking forward to meeting you!

**Comment by encukou** [comment]
@willingc @JulienPalard The meeting is starting in 90 minutes, but I don't see you on Discord. If you're having trouble connecting, let me know; maybe I can help.

**Comment by JulienPalard** [comment]
I'm here, I just can't join the room because "I have to wait 10mn" :(

**Comment by encukou** [comment]
Meeting minutes are at: https://docs-community.readthedocs.io/en/latest/monthly-meeting/2022-02.html

**Comment by AA-Turner** [comment]
> (& other active PEP editors): I wonder if you'd be interested in the [documentation working group](https://docs-community.readthedocs.io/en/latest/workgroup/workgroup_charter.html). 

@encukou I'd be interested in joining as one of the PEP Editors, although I'm not sure what would be expected of me or what the joining process is - happy to talk wherever if need be?

A
