### ISSUE TITLE
Docs WG monthly meeting #2

### ISSUE THREAD

**Issue by encukou** [python/docs-community#20]
The second Docs WG meeting will be held **Monday, March 7th, [22:00 UTC](https://www.timeanddate.com/worldclock/fixedtime.html?iso=20220207T2200)** on Discord. If you already have an account there, please join with `sMWqvzXvde`. Or contact me at [encukou@gmail.com](mailto:encukou@gmail.com) for a direct link -- this should be public, but I want to avoid any invite-harvesting bots.

I've cleaned up the HackMD document, so we can reuse it. Feel free to add agenda items there: https://hackmd.io/_vyolH-NR3GQHoOUjqdzuQ

**Comment by pauleveritt** [comment]
Apologies, I didn't look correctly at the time. I coach a girls sport and I'll still be on the field. Go ahead without me, I'll try to get my WG stuff in place async.

**Comment by pradyunsg** [comment]
Can we pin this issue?

**Comment by pradyunsg** [comment]
Keeping this open until we have the meeting notes published. :)

**Comment by pradyunsg** [comment]
I can't unpin this issue! :)
