### ISSUE TITLE
Discourse: fill in "About the Documentation category"

### ISSUE THREAD

**Issue by hugovk** [python/docs-community#23]
The pinned about page for the Documentation category still has the template placeholder:

https://discuss.python.org/t/about-the-documentation-category/5499

> (Replace this first paragraph with a brief description of your new category. This guidance will appear in the category selection area, so try to keep it below 200 characters.)
> 
> - Use the following paragraphs for a longer description, or to establish category guidelines or rules:
> 
> - Why should people use this category? What is it for?
> 
> - How exactly is this different than the other categories we already have?
> 
> - What should topics in this category generally contain?
> 
> - Do we need this category? Can we merge with another category, or subcategory?

Let's update it.

**Comment by AA-Turner** [comment]
There are talks about enabling GH Discussions -- I think we should synchronise the welcome / about messages for both if possible. 

Ideally, we'd also clarify if `discuss.` and Discussions are for different things, or just two equivilent fora for people who prefer one or the other.

A

**Comment by encukou** [comment]
So, what do we want there? I started a pad here: https://hackmd.io/BBXNZe6aTXq28LqpkIWfhw

**Comment by pauleveritt** [comment]
I suggest shipping it and closing this ticket. Any further improvements can be made in the normal course of things.

That said, a question and a minor suggestion. First, should the Discourse be a place to discuss the actual documentation content? Or should that be in tickets? I presume translations are similar.

Second, perhaps mention the "who". The Discourse is for anybody that feels a part of docs contribution, including consumers giving feedback.

**Comment by encukou** [comment]
> I suggest shipping it and closing this ticket. Any further improvements can be made in the normal course of things.

Changing this is annoying without a Discourse admin on board, so I'd rather take some time in getting something we all agree on.

> First, should the Discourse be a place to discuss the actual documentation content? Or should that be in tickets?

I reworded it to use tickets for issues “which don't need <ins>wide</ins> discussion”.

>  I presume translations are similar.

I added a link to the list of individual translations, and noted that this is a good place to organize a new translation.

---

> [name=CAM,  in the pad] Going to need an update very soon now that the BPO -> GH move is imminent 

I'm pretty sure there'll be a redirect.

**Comment by encukou** [comment]
I've [posted the draft in Discourse thread](https://discuss.python.org/t/draft-introduction-for-the-documentation-category/14255).

**Comment by CAM-Gerlach** [comment]
I made a few additional copyedits to fix a couple grammar and phrasing issues, link to the PEPs like the other two, and reword "consumers" to "readers" which is much friendlier, more appropriate and widely understood.

> I'm pretty sure there'll be a redirect.

Yeah, though the linked text explicitly says "bugs.python.org".

**Comment by encukou** [comment]
This is [done](https://discuss.python.org/t/about-the-documentation-category/5499)! Thanks for the input, everyone!

**Comment by CAM-Gerlach** [comment]
Thanks for the taking the initiative on this, @encukou !
