### ISSUE TITLE
docs-community: Enable preview rendering for pull requests

### ISSUE THREAD

**Issue by AA-Turner** [python/docs-community#28]
Given this project is using read the docs, we may as well use PR preview rendering.

I don't know who is an admin of the project on RTD, though -- @willingc perhaps?

A

**Comment by pradyunsg** [comment]
The only person with access to the RTD pages is @willingc: https://readthedocs.org/projects/docs-community/

There's a "Build pull requests for this project" checkbox on [this page](https://readthedocs.org/dashboard/docs-community/advanced/). You will also need to click save at the end of the page before closing it.

We probably wanna also increase our bus factor for the RTD page. You can add more folks on [this page](https://readthedocs.org/dashboard/docs-community/users/) as long as you know their RTD usernames. :)

**Comment by encukou** [comment]
Mariatta and I have access now. Thanks Carol!
I've completed the setup for PR previews, you can check it in https://github.com/python/docs-community/pull/37 :)
