### ISSUE TITLE
Post the application process for workgroup members

### ISSUE THREAD

**Issue by willingc** [python/docs-community#3]
We'll be modeling this after the application process for Code of Conduct workgroup members. See https://mail.python.org/pipermail/psf-community/2018-April/000488.html as an example

**Comment by pradyunsg** [comment]
Any updates on this? Did this happen, and I missed it? :)

**Comment by willingc** [comment]
@pradyunsg We're in the final review of an application form to share with the community. We'll make sure to announce broadly when it is live to the community. Thanks for asking. :sunny:

**Comment by pradyunsg** [comment]
Hiya! A gentle nudge on this. Anything I can do to help make this happen? :)

@pauleveritt reached out recently, expressing his interest in contributing to this WG/CPython documentation as well.

**Comment by pauleveritt** [comment]
Yep, count me in.

**Comment by pradyunsg** [comment]
This was discussed at some length in the May 2022 meeting for the documentation community team.

https://docs-community.readthedocs.io/en/latest/monthly-meeting/2022-05.html#the-vision-of-docs-wg-with-carol-willing
