### ISSUE TITLE
What's the intended organisation of people here?

### ISSUE THREAD

**Issue by pradyunsg** [python/docs-community#31]
So... this morning I'm spiralling into what is almost certainly going to end up being a proposal on python-ideas or the Ideas category on discuss.python.org -- that we adopt the ["Teams" concept from PEP 8015](https://peps.python.org/pep-8015/).

And... that has confused me about this group -- is the plan for this group to become a PSF [work group](https://www.python.org/psf/committees/) (i.e. PSF board approved group, fundraising + making hiring decisions, handle all the paperwork around that etc), or is this intended to be closer to what the typing has (just a bunch of volunteers who are interested in the topic), or what the packaging community has (both, with a clear separation between the two)?

I'm thinking that this group will have a similar split in responsibilities as [Packaging-WG](https://wiki.python.org/psf/PackagingWG) and the [PyPA](https://www.pypa.io/en/latest/) (see https://peps.python.org/pep-0609/#terminology for language on the relationship).

Filing this on the issue tracker, to serve as a clear place for public discussion on this. :)

**Comment by pradyunsg** [comment]
I'm mostly asking for a clarification because I'm pretty sure that I don't want to be on the WG, but I do want to collaborate with the folks here to actually make improvements to the actual documentation. :)

**Comment by encukou** [comment]
This (*docs-community*) is an informal group, like typing-sig.
The *Docs WG* is to be a PSF workgroup.
Personally I think it's more important to build the community than the authority.

**Comment by pradyunsg** [comment]
Thanks for the clarification @encukou!

I guess we'll move the contents of https://github.com/python/docs-community/tree/main/docs/workgroup to the wiki, whenever the PSF board ends up voting on the workgroup. Good to know! :)

**Comment by pradyunsg** [comment]
I've written up the thing I alluded to in the first post about teams: https://discuss.python.org/t/adopting-the-concept-of-teams-from-pep-8015/14210

That has a link to this issue.

**Comment by pauleveritt** [comment]
I don't mind helping on something more official like a WG. But I feel like I have to put on a different hat when doing so. Thus I'm glad you're pushing to clarify it. I agree with @encukou that we are acting like a SIG until further notice.

**Comment by pradyunsg** [comment]
Closing this since the question has been answered! :)

Thanks again @encukou!

**Comment by pradyunsg** [comment]
There's been some more discussion about this in today's meeting, where certain clarifications were made. https://github.com/python/docs-community/pull/51 adds the notes from that meeting into the repository.
