### ISSUE TITLE
Shut down and archive https://legacy.python.org/

### ISSUE THREAD

**Issue by encukou** [python/docs-community#36]
This came up at the 2021 Language Summit.
“Thomas and Ee to address.”

**Comment by CAM-Gerlach** [comment]
On a minor sidenote, this came up on the [PEPs repo](https://github.com/python/peps/pull/2286#discussion_r795233942).

**Comment by CAM-Gerlach** [comment]
Funny enough, this just came up in python/peps#2431 ; @smontanaro updated a link in PEP 339 to a paper of his to point to legacy.python.org, and I can't seem to find an equivalent on python.org or another canonical source. Maybe we need to have a subdirectory or subdomain to archive selected old but still potentially useful material like this that doesn't have a direct replacement on the current site, perhaps with redirects as appropriate?

**Comment by smontanaro** [comment]
Not sure what the argument for shutting down the legacy site is. If it's to go away, maybe the webserver can redirect references elsewhere, Wayback Machine perhaps?

**Comment by encukou** [comment]
It seems Thomas and Ee are @yhg1s and @ewdurbin. Is that right? Do you know more about this action item?

To me, seeing pages like [the mentioned paper](https://legacy.python.org/workshops/1998-11/proceedings/papers/montanaro/montanaro.html) it seems like properly sunsetting `legacy` would be a big pile of work. Is there a plan you know of?

**Comment by gvanrossum** [comment]
Yeah, I probably have some stuff there too (though I'd be happy to move it to my personal home page).

**Comment by ewdurbin** [comment]
legacy.python.org is now served from a static mirror. I don't believe taking it offline is prudent.

The apache configuration to serve that mirror is at https://github.com/python/psf-salt/blob/main/salt/hg/config/legacy.apache.conf.jinja, so new redirects could be added to slowly migrate content away.

But for the purposes of this issue (that the host in XS4ALL needed to be decommissioned) I think it can be closed.

**Comment by Yhg1s** [comment]
Indeed, the host is well and truly shut down: https://twitter.com/Yhg1s/status/1423629453461270533

**Comment by ewdurbin** [comment]
> If that's the goal, IMO it would be best to put the archive up as a repo on GitHub (excluding `secret/` of course). AFAICS, a PSF staff member would need to release the data. (Scraping won't catch unlinked pages.)

The archive in total is ~1GB... so I'm not sure how feasible it is to make it a repo on GitHub unless people expressly want to do the work.

**Comment by CAM-Gerlach** [comment]
There's your [essays](https://legacy.python.org/doc/essays/), though they are also found [on the modern Python site](https://www.python.org/doc/essays/), and there is your [list of presentations](https://legacy.python.org/doc/essays/ppt/), which I can't find on the modern site. Probing various forms/combinations of your name as subdirs didn't appear to reveal anything.

**Comment by gvanrossum** [comment]
@ewdurbin Could you do me a favor and send me a dump of the "ppt" directory CAM mentioned? (It's served as https://legacy.python.org/doc/essays/ppt/.) I'd like to have those on my personal website.

**Comment by ewdurbin** [comment]
@gvanrossum that archive has been emailed to you.

**Comment by gvanrossum** [comment]
Thanks! These are now at https://gvanrossum.github.io/essays/ppt/index.html.
