### ISSUE TITLE
Review bpo-21314: Document '/' in signatures

### ISSUE THREAD

**Issue by iritkatriel** [python/docs-community#42]
[An old open issue](https://bugs.python.org/issue21314) that you may be able to resolve.

**Comment by CAM-Gerlach** [comment]
Thanks, I opened python/peps#2479 to discuss marking the PEP "Final" and anything else that should be moved to a more canonical location. As it seems the [language spec](https://docs.python.org/3/reference/compound_stmts.html#function-definitions) was updated to mention it and the [FAQ entry](https://docs.python.org/3/faq/programming.html#what-does-the-slash-in-the-parameter-list-of-a-function-mean) was revised following that issue to not link to the PEP and be a self-contained explanation, and the other comments relate to the `pydoc` tool, I'm not sure whether there's anything left to do from a documentation perspective.

**Comment by encukou** [comment]
IMO, what's left is ensuring that searching for `/` will give you the explanation, but that's #39.
