### ISSUE TITLE
Review bpo-36329: use the right python "make -C Doc/ serve"

### ISSUE THREAD

**Issue by iritkatriel** [python/docs-community#45]
[An open issue](https://bugs.python.org/issue36329) that you may be able to resolve.

**Comment by hugovk** [comment]
The CPython one has been merged, devguide is still open.

**Comment by AA-Turner** [comment]
This is now https://github.com/python/cpython/issues/80510, discussion should happen on that issue as noted in the May 2022 meeting.

A
