### ISSUE TITLE
Migrate these docs to docs-community.python.org

### ISSUE THREAD

**Issue by willingc** [python/docs-community#53]

**Comment by AA-Turner** [comment]
Is `docs-community.python.org` an invariant? I think it's fine as a group name, but feels clunky in a domain -- though I don't have many better sugggestions (`docsguide`? `docsteam`? `docscommunity` (no hyphen)?).

A

**Comment by willingc** [comment]
I'm open to suggestions.

**Comment by CAM-Gerlach** [comment]
This should just be a matter of putting it behind Fastly like we do for the PEPs, right @ewdurbin ?

**Comment by ewdurbin** [comment]
No. I would suggest using RTD directly. I'm happy to setup the DNS record to point whatever the chosen domain is to RTD.

If the EWDurbin User (me) on RTD is added to the project with the Administrator level privileges I can perform this work and maintain it as any changes occur on the infra side.

**Comment by pradyunsg** [comment]
[^1]

Could someone clarify the motivation for doing this? My guess is that it's to make the pages more "official", and giving them greater authority -- but a confirmation of whether that's right/wrong would be nice. :)

> `docsteam`

I read this as doc steam on the first pass. A hypen would be nice. But, I also wanna avoid triggering a bikesheddy discussion, so I'll refrain from saying more on that aspect.

[^1]: Looks like I closed my tab before posting the comment draft I had. :/

**Comment by CAM-Gerlach** [comment]
> I read this as doc steam on the first pass. A hypen would be nice. But, I also wanna avoid triggering a bikesheddy discussion, so I'll refrain from saying more on that aspect.

I did as well. FWIW, for the average user I'd think `docs-community` is probably the clearest, most appropriate and easiest to read of the options. Since its just a subdomain, redirecting the non-hyphenated version to the canonical one should be very cheap, I'd think.

**Comment by encukou** [comment]
I agre that `docs-community` seems clearer than the no-hyphen version, and `docs-team` isn't worth not using the repo name.
As for `docsguide` – IMO, the actual guide should be in the devguide :)

**Comment by ezio-melotti** [comment]
`docswg`?

**Comment by CAM-Gerlach** [comment]
:laughing:

**Comment by willingc** [comment]
Closing as this has been moved to RTD hosting.

**Comment by StanFromIreland** [comment]
> No. I would suggest using RTD directly. **I'm happy to setup the DNS record to point whatever the chosen domain is to RTD.**
> 
> If the EWDurbin User (me) on RTD is added to the project with the Administrator level privileges I can perform this work and maintain it as any changes occur on the infra side.

Maybe this should be reopened, it was never really completed?
