### ISSUE TITLE
Suggestions from Python Language Summit

### ISSUE THREAD

**Issue by willingc** [python/docs-community#6]
1. From Greg Smith:
> we should turn this into a modern "how to write a modern interpreter finalization and subinterpreter safe extension module" best practices doc.  (beyond the pep)

**Comment by willingc** [comment]
2. From Scott Shawcroft:

> Look into improving python.org search to also search the docs.

**Comment by willingc** [comment]
3. From discussion:

> Shut down and archive https://legacy.python.org/

**Comment by encukou** [comment]
1. I assume this is about [PEP 630](https://peps.python.org/pep-0630/). Converting it to a HOWTO is bubbling up on my TODO list, and integrating it in the docs is next, after solving the [Type Checking](https://peps.python.org/pep-0630/#type-checking) open issue. No need to track it here, but if anyone wants to help, let me know.
2. → https://github.com/python/docs-community/issues/35
3. → https://github.com/python/docs-community/issues/36
