### ISSUE TITLE
Re-enable deprecation warnings

### ISSUE THREAD

**Issue by encukou** [python/docs-community#70]
Warnings were *temporarily* disabled in https://github.com/python/docs-community/pull/69. They should be re-enabled.

https://github.com/python/docs-community/issues/70#tasklist-block-5fc69310-1c5c-4a60-b3a6-ad4deb5735be

**Comment by hugovk** [comment]
Yep, we can re-enable when this Sphinx issue is fixed: https://github.com/sphinx-doc/sphinx/issues/10440.

**Comment by CAM-Gerlach** [comment]
We could probably edit the title to reflect the conditional...

**Comment by ezio-melotti** [comment]
@encukou, if you edit the first message and add the link to https://github.com/sphinx-doc/sphinx/issues/10440  in a check/task list, it will be tracked automatically and once the issue is solved it will show as "1 of 1 task completed" (or something similar).
