### ISSUE TITLE
[PyCon 2024] Documentation summit and Documentation sprint

### ISSUE THREAD

**Issue by Cheukting** [python/docs-community#78]
I would like to propose these activities for PyCon 2024, I know it is not relevant to the documentation for Python but I would like to get the opinion of the amazing people who are passionate about documentation and put in so much effort to make our documentation great!

### Documentaion summit

Like other summits, we will invite leaders in the documentation spaces (especially in the Python community) to present some documentation-focused talks. We will also host panel sessions to discuss relevant issues regarding documentation. It would also be great to invite tech writers from companies (e.g. sponsors, those who have good documentation) to join.

### Documentation sprint

It can be part of the "regular" sprint at the end of the conference, however, we should gather projects to put focus on documentation and encourage contribution to it. Or it can be like mentored sprints and have a separate session in the tutorials/ main conference days.

Please let me know what you think. CC @Mariatta who is the awesome PyCon chair of 2023 and 2024

**Comment by nedbat** [comment]
I think there would be a lot of interest in this!  But I'm curious why you said this:
> I know it is not relevant to the documentation for Python

There's real (and growing) energy now behind new approaches to the CPython docs. This summit would be a good place to bring the interested people together.

**Comment by Cheukting** [comment]
Ah, I meant to say it is not directly relevant 😂 - of cause it is relevant. Thank you for the support @nedbat

**Comment by CAM-Gerlach** [comment]
Hi @Cheukting ; great to see your proposal for this! @Mariatta had previously mentioned your interest to us on the Docs Community Discord, and I'd been thinking of proposing something like that too based on people's feedback (at my PyCon Docs talk and elsewhere) and the success of the Packaging Summits we've organized for the past couple years.

The docs summit sounds like a terrific idea and I'm happy to help with the backend logistics (announcements, timelines, checklists, forms, scheduling, procedures, notes, web page, etc) taking advantage the templates and processes we've developed and refined over the years from running the PyCon packaging summit, to ensure that all goes smoothly with minimal extra effort.

As for sprints, we did have a number of mentors, contributors and maintainers working on docs, PEPs, devguide, etc. at the mentored and regular CPython sprints over the past two years as well, and it would be great to expand that further! ISTM that it would be best to integrate it as part of the existing mentored/sprints given limited time, resources and schedule availability during the conference, but I would of course course defer to your much greater experience and ideas on that and am happy to help support however needed.

@cmaureir and @humitos on there also expressed interest as well, particularly from the translation perspective as it would be fantastic to see more collaboration between translation teams and between the translation teams and the rest of the docs community.

I've created two new channels, #summit and #sprints on the Docs Community Discord that you're welcome to [welcome to join](https://discord.gg/sMWqvzXvde) (if you haven't already) to coordinate this going forward, as has worked well for the Packaging Summit. While probably it won't be necessary to start planning for the PyCon US 2024 sprints and summit in earnest until November or December 2023, hopefully people can use those to pan sprints and summits at other conferences as well!

**Comment by willingc** [comment]
Just a quick update on this one. The proposal was accepted for the Hatchery at PyCon 2024. Thanks @Cheukting for making this happen.

**Comment by willingc** [comment]
Another update. Posted on the PyCon site: https://us.pycon.org/2024/events/hatchery/docs-summit/

**Comment by hugovk** [comment]
This happened! Thanks all!
