### ISSUE TITLE
Help needed: Community platform

### ISSUE THREAD

**Issue by satyampsoni** [python/docs-community#88]
Is there any slack or Discord official community of Python?

**Comment by Mariatta** [comment]
There is a Discourse forum https://discuss.python.org

**Comment by egeakman** [comment]
Hi, great to see your interest in the Python community!

- If you're looking for the documentation community, you can check [this link](https://docs-community.readthedocs.io/en/latest/community/contributing.html#get-connected) out for some options.
- If you're looking for a general Python community [this Discord server](https://discord.gg/python) or [the Discourse forum](https://discuss.python.org) might be the right place to go.

**Comment by satyampsoni** [comment]
Thanks for sharing @Mariatta @egeakman
