### ISSUE TITLE
French translation sprint

### ISSUE THREAD

**Issue by ygingras** [python/docs-community#9]
Posting here for added visibility.

The Montréal-Python user group is hosting a sprint to work the on the French translation of the Python documentation until the end of the month. We are focussing on 3.9 for this sprint with aspirations to run another one in the fall to focus on 3.10.

More details here: https://mtlpy.org/en/2021/04/python-fr-sprint/

**Comment by AA-Turner** [comment]
Closing as the event finished on 31/05/2021.

A
